runtime: python
env: flex
service: healthcarenewOrExistingPatient
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

env_variables:
    BASE_URL: 'https://healthcare.googleapis.com/v1'
    PROJECT_ID: '<Your Project ID>'
    REGION: us-central1
    DATASET_ID: temp
    FHIR_STORE_ID: t
